.Dd $Mdocdate: April 10 2021 $
.Dt KNFMT 1
.Os
.Sh NAME
.Nm knfmt
.Nd kernel normal form formatter
.Sh SYNOPSIS
.Nm
.Op Fl dis
.Op Ar
.Nm
.Op Fl Ddis
.Sh DESCRIPTION
The
.Nm
utility formats source code files to conform to the Kernel Normal Form (KNF) in
a best effort fashion, see
.Xr style 9 .
.Pp
The options are as follows:
.Bl -tag -width "file"
.It Fl D
Only format changed lines extracted from a diff read from standard input.
.It Fl d
Produce a diff for each given
.Ar file .
.It Fl i
In place edit of
.Ar file .
.It Fl s
Simplify the source code.
.It Ar file
One or many files to format.
If omitted, defaults to reading from standard input.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr style 9
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
