/*
 * Copyright (c) 2025 Anton Lindqvist <anton@basename.se>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef LIBKS_CAPABILITIES_H
#define LIBKS_CAPABILITIES_H

#include <stdint.h>

#define CPUID_01_C_SSE3_0_MASK		(1u << 9)
#define CPUID_01_C_SSE4_1_MASK		(1u << 19)
#define CPUID_01_C_SSE4_2_MASK		(1u << 20)
#define CPUID_01_C_OSXSAVE_MASK		(1u << 27)
#define CPUID_01_C_AVX_MASK		(1u << 28)

#define CPUID_01_D_SSE1_0_MASK		(1u << 25)
#define CPUID_01_D_SSE2_0_MASK		(1u << 26)

#define CPUID_07_B_FSGSBASE_MASK	(1u << 0)
#define CPUID_07_B_BMI1_MASK		(1u << 3)
#define CPUID_07_B_AVX2_MASK		(1u << 5)
#define CPUID_07_B_BMI2_MASK		(1u << 8)
#define CPUID_07_B_AVXF_MASK		(1u << 16)
#define CPUID_07_B_AVXBW_MASK		(1u << 30)

#define CPUID_0x80000001_C_LZCNT_MASK	(1u << 5)

#define XCR0_XMM_MASK			(1u << 1)
#define XCR0_YMM_MASK			(1u << 2)
#define XCR0_OPMASK_MASK		(1u << 5)
#define XCR0_ZMM_HI256_MASK		(1u << 6)
#define XCR0_HI16_ZMM_MASK		(1u << 7)

enum KS_x86_uarch {
	KS_X86_UNKNOWN,

	KS_X86_INTEL_CORE_YONAH,
	KS_X86_INTEL_CORE2_MEROM,
	KS_X86_INTEL_CORE2_PENRYN,
	KS_X86_INTEL_NEHALEM_EP,
	KS_X86_INTEL_BONNELL,
	KS_X86_INTEL_CORE2_DUNNINGTON,
	KS_X86_INTEL_NEHALEM,
	KS_X86_INTEL_WESTMERE,
	KS_X86_INTEL_BONNELL_MID,
	KS_X86_INTEL_SALTWELL_MID,
	KS_X86_INTEL_SANDYBRIDGE,
	KS_X86_INTEL_WESTMERE_EP,
	KS_X86_INTEL_NEHALEM_EX,
	KS_X86_INTEL_WESTMERE_EX,
	KS_X86_INTEL_SALTWELL_TABLET,
	KS_X86_INTEL_SALTWELL,
	KS_X86_INTEL_SILVERMONT,
	KS_X86_INTEL_IVYBRIDGE,
	KS_X86_INTEL_HASWELL,
	KS_X86_INTEL_BROADWELL,
	KS_X86_INTEL_SILVERMONT_MID,
	KS_X86_INTEL_AIRMONT,
	KS_X86_INTEL_SKYLAKE,
	KS_X86_INTEL_CASCADELAKE,
	KS_X86_INTEL_COOPERLAKE,
	KS_X86_INTEL_XEON_PHI_KNL,
	KS_X86_INTEL_SILVERMONT_MID2,
	KS_X86_INTEL_GOLDMONT,
	KS_X86_INTEL_CANNONLAKE,
	KS_X86_INTEL_ICELAKE,
	KS_X86_INTEL_AIRMONT_NP,
	KS_X86_INTEL_GOLDMONT_PLUS,
	KS_X86_INTEL_XEON_PHI_KNM,
	KS_X86_INTEL_TREMONT,
	KS_X86_INTEL_TIGERLAKE,
	KS_X86_INTEL_KABYLAKE,
	KS_X86_INTEL_AMBERLAKE,
	KS_X86_INTEL_COFFEELAKE,
	KS_X86_INTEL_WHISKEYLAKE,
	KS_X86_INTEL_SAPPHIRERAPIDS,
	KS_X86_INTEL_LAKEFIELD,
	KS_X86_INTEL_ALDERLAKE,
	KS_X86_INTEL_ICELAKE_NNPI,
	KS_X86_INTEL_METEORLAKE,
	KS_X86_INTEL_GRANITERAPIDS,
	KS_X86_INTEL_CRESTMONT,
	KS_X86_INTEL_ARROWLAKE,
	KS_X86_INTEL_RAPTORLAKE,
	KS_X86_INTEL_GRACEMONT,
	KS_X86_INTEL_COMETLAKE,
	KS_X86_INTEL_ROCKETLAKE,
	KS_X86_INTEL_LUNARLAKE,
	KS_X86_INTEL_PANTHERLAKE,
	KS_X86_INTEL_EMERALDRAPIDS,
	KS_X86_INTEL_WILDCATLAKE,
	KS_X86_INTEL_BARTLETTLAKE,
	KS_X86_INTEL_DARKMONT,
	KS_X86_INTEL_NOVALAKE,
	KS_X86_INTEL_DIAMONDRAPIDS,
};

struct KS_x86_capabilites {
	enum KS_x86_uarch uarch;
	uint32_t mode;
	uint32_t avx;
	uint32_t bmi;
	uint32_t sse;
	uint32_t fsgsbase:1,
		 lzcnt:1;

	struct {
		uint32_t bw:1;
	} avx512;
};

const struct KS_x86_capabilites *KS_x86_capabilites(void);

#endif /* !LIBKS_CAPABILITIES_H */
