name: coverity scan

on:
  push:
    branches: [master, coverity]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: configure
      env:
        CFLAGS: -O2
      run: ./configure
    - name: coverity
      uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
