name: test

on:
  - push
  - pull_request

jobs:
  linux-gcc-asan-ubsan:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CFLAGS: -Wformat-signedness
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-clang-asan-ubsan:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
        run: |
          ./configure --pedantic
          make -j`nproc` test

  macos-clang-asan-ubsan:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
        run: |
          ./configure --pedantic
          make -j`sysctl -n hw.logicalcpu` test

  valgrind:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install valgrind
      - name: test
        env:
          CC: gcc
          EXEC: valgrind
          VALGRIND_OPTS: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all
        run: |
          ./configure --pedantic
          make -j`nproc` test

  musl:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install musl-tools
      - name: test
        env:
          CC: musl-gcc
        run: |
          ./configure --pedantic
          make -j`nproc` test

  ndebug:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DNDEBUG
        run: |
          ./configure --pedantic
          make -j`nproc` test

  fuzz:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install afl
      - name: test
        env:
          CC: afl-gcc
        run: |
          ./configure --pedantic
          make -j`nproc` fuzz

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clang-tidy
        run: |
          ./configure
          make lint-clang-tidy

  cppcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install cppcheck
      - name: cppcheck
        run: |
          ./configure
          make lint-cppcheck
