name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        mode: [asan, ubsan, musl, valgrind]
        exclude:
          - os: macos-latest
            compiler: gcc

          - mode: musl
            os: macos-latest

          - mode: musl
            os: ubuntu-latest
            compiler: clang

          - mode: valgrind
            os: macos-latest

          - mode: valgrind
            os: ubuntu-latest
            compiler: clang

        include:
          - os: ubuntu-latest
            deps_os: uthash-dev
            nproc: nproc

          - os: macos-latest
            nproc: sysctl -n hw.logicalcpu

          - compiler: gcc
            cflags: -Wformat-signedness

          - mode: asan
            debug: -fsanitize=address

          - mode: ubsan
            debug: -fsanitize=undefined -fno-sanitize-recover=all

          - mode: musl
            cc: musl-gcc
            deps_mode: musl-tools
            musl: 1

          - mode: valgrind
            deps_mode: valgrind
            exec: valgrind
            valgrind: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all

    steps:
      - uses: actions/checkout@v2

      - name: dependenices
        if: ${{matrix.deps_os || matrix.deps_mode}}
        run: sudo apt-get update && sudo apt-get install ${{matrix.deps_os}} ${{matrix.deps_mode}}

      - name: test
        env:
          CC: ${{matrix.cc || matrix.compiler}}
          CFLAGS: -Werror -Wpedantic -Wshadow -Wwrite-strings ${{matrix.cflags}}
          CPPFLAGS: ${{matrix.cppflags}}
          DEBUG: -g -O2 ${{matrix.debug}}
          EXEC: ${{matrix.exec}}
          MUSL: ${{matrix.musl}}
          VALGRIND_OPTS: ${{matrix.valgrind}}
        run: |
          set -ex
          ${CC} -v
          MAKE="make -j `${{matrix.nproc}}`"
          ./configure || :
          cat config.log
          ${MAKE} test
          # Ensure assertions are free from side effects.
          env CPPFLAGS="${CPPFLAGS} -DNDEBUG" ./configure || :
          cat config.log
          ${MAKE} test
